### ISSUE TITLE
Hacktoberfest tag

### ISSUE THREAD

**Issue by thesilican** [Gjergj/hacktober-blackhole#8]
You gotta add the `hacktoberfest` topic to the repository otherwise pull requests won't count!!

[Hacktoberfest rules](https://hacktoberfest.digitalocean.com/details)

[How to add GitHub Topics to repository](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by Gjergj** [comment]
Thanks
Added the topic
